### ISSUE TITLE
Commands with 'brew cask install' need to be changed to 'brew install cask'  -- same for uninstall

### ISSUE THREAD

**Issue by Lee-Hounshell-at-MarianaTek** [Mariana-Tek/laptop#3]
On MacOS Catalina the 'mac' script fails on lines beginning with 'brew cask install'   If the commands are edited to begin with 'brew install cask' the script runs.   I made similar changes for uninstall, but did not test that.

**Comment by bashhack** [comment]
Thanks @Lee-Hounshell-at-MarianaTek - it looks like on December 15, 2020 there was an upstream change from Homebrew that disabled that prior cask command format - thanks for raising!

@arbonap just posted a fix as we were working through it (:tada:) so this is now updated, uninstall changes coming soon too :)

**Comment by bashhack** [comment]
For reference, first round of changes: https://github.com/Mariana-Tek/laptop/pull/5
